# Generated by Django 6.0 on 2025-12-10 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكلية')),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'الكلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط المختصر')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(max_length=500, verbose_name='مقتطف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_popular', models.BooleanField(default=False, verbose_name='شائع')),
                ('is_for_students', models.BooleanField(default=False, verbose_name='موجه للطلاب')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد للنشر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='المقال')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'تعليقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
