# Generated by Django 6.0 on 2025-12-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'معتمد للنشر'), ('PENDING', 'قيد المراجعة'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=160, verbose_name='وصف المقال'),
        ),
    ]
