# Generated by Django 6.0 on 2025-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_is_approved_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=150, verbose_name='التعليق'),
        ),
    ]
